### ISSUE TITLE
namespacedName error

### ISSUE THREAD

**Issue by esemve** [FriendsOfPHP/Sami#252] opened 2016-12-16 16:19 UTC
Hello!

When I try generate a documentation from my project with the phpunit vendor, this say:

 [ErrorException]
  Notice: Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in /var/www/test/NodeVisitor.php line 114

(I try generate from the full Laravel - just for demo)

**Comment by aik099** [comment] 2016-12-16 17:24
Please specify output of `composer show -i` command and sami config content that you use.

**Comment by esemve** [comment] 2016-12-19 13:30
? Composer? I use Sami from phar.

The problem is with this packages:
```
phpunit/php-code-coverage             2.2.4   Library that provides collect...
phpunit/php-file-iterator             1.4.1   FilterIterator implementation...
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.8   Utility class for timing
phpunit/php-token-stream              1.4.8   Wrapper around PHP's tokenize...
phpunit/phpunit                       4.8.27  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          2.3.8   Mock Object library for PHPUnit
```


My config:

```
<?php
use Sami\Sami;
use Sami\RemoteRepository\GitHubRemoteRepository;
use Symfony\Component\Finder\Finder;

$iterator = Finder::create()
    ->files()
    ->name('*.php')
    ->exclude('Resources')
    ->exclude('Tests')
    ->in('/mnt/sdb1/webserver/testsite/vendor/phpunit/')
;

return new Sami($iterator);
```

Output:
```root@nostromo:/var/www/test2# php sami.phar update config.php --force
 Updating project

Version master
  Parsing # 3%                                                  1 error
          Foo


  [ErrorException]
  Notice: Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in phar:///var/www/test2/sami.phar/Sami/Parser/NodeVisitor.php line 114
```

**Comment by aik099** [comment] 2016-12-19 14:08
I mean full output of `composer show -i` command, not the part of it as you did 😉 

What I was interested in is used PHP-Parser version.

**Comment by esemve** [comment] 2016-12-19 14:13
I used the phar :) 
But I get from this repository now, and same error.

```
blackfire/php-sdk                 v1.6.0          Blackfire.io PHP SDK
composer/ca-bundle                1.0.6           Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
michelf/php-markdown              1.7.0           PHP Markdown
nikic/php-parser                  v3.0.2          A PHP parser written in PHP
phpdocumentor/reflection-docblock 2.0.4
pimple/pimple                     v3.0.2          Pimple, a simple Dependency Injection Container
psr/log                           1.0.2           Common interface for logging libraries
symfony/console                   v3.2.1          Symfony Console Component
symfony/debug                     v3.2.1          Symfony Debug Component
symfony/filesystem                v3.2.1          Symfony Filesystem Component
symfony/finder                    v3.2.1          Symfony Finder Component
symfony/phpunit-bridge            v3.2.1          Symfony PHPUnit Bridge
symfony/polyfill-mbstring         v1.3.0          Symfony polyfill for the Mbstring extension
symfony/process                   v3.2.1          Symfony Process Component
symfony/yaml                      v3.2.1          Symfony Yaml Component
twig/twig                         2.x-dev dc36ae3 Twig, the flexible, fast, and secure template language for PHP
```

**Comment by aik099** [comment] 2016-12-19 14:14
> I used the phar :)

My apologies, haven't noticed that initially while reading your response.

Maybe you can post minimal PHP code fragment to reproduce the issue?

**Comment by esemve** [comment] 2016-12-19 14:22
Yes, for example (phpunit/php-token-streamer):

```
<?php
namespace Foo\Bar;

class TestClassInBar
{
}

namespace Foo\Baz;

class TestClassInBaz
{
}
```

```
<?php
namespace Foo\Bar
{
    class TestClassInBar
    {
    }
}

namespace Foo\Baz
{
    class TestClassInBaz
    {
    }
}
```

**Comment by aik099** [comment] 2016-12-19 14:24
File with 2+ namespaces in it. I see.

Was it working in previous Sami versions (1.x or 2.x)?

**Comment by esemve** [comment] 2016-12-19 14:34
Yes, 1.4-DEV is work fine

**Comment by aik099** [comment] 2016-12-19 14:39
Can you please (if possible) do `git bisect` (see https://git-scm.com/docs/git-bisect) on Sami code in `master` branch (starting from last known working commit till `head` commit) and check if it it works to figure out commit that breaks that?

For now my best guess would be something changed in PHP-Parser that we haven't accounted for.

**Comment by esemve** [comment] 2016-12-19 15:24
The last good commit is: 5e31696453125c71e86718c35950450988e87e3a

Composer:
```
michelf/php-markdown      1.7.0   PHP Markdown
nikic/php-parser          v0.9.5  A PHP parser written in PHP
pimple/pimple             v2.1.1  Pimple is a simple Dependency Injection Container for PHP 5.3
psr/log                   1.0.2   Common interface for logging libraries
symfony/console           v2.8.15 Symfony Console Component
symfony/debug             v3.0.9  Symfony Debug Component
symfony/filesystem        v2.8.15 Symfony Filesystem Component
symfony/finder            v2.8.15 Symfony Finder Component
symfony/polyfill-mbstring v1.3.0  Symfony polyfill for the Mbstring extension
symfony/process           v2.8.15 Symfony Process Component
symfony/yaml              v2.8.15 Symfony Yaml Component
twig/twig                 v1.29.0 Twig, the flexible, fast, and secure template language for PHP
```


The first bad is: 735b41605b6866e81bc2627a189def78cbb1c3c3
Packages:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing pimple/pimple (v3.0.2)
    Loading from cache

  - Installing twig/twig (v1.29.0)
    Loading from cache

  - Installing nikic/php-parser (v1.4.1)
    Loading from cache

  - Installing michelf/php-markdown (1.7.0)
    Loading from cache

  - Installing psr/log (1.0.2)
    Loading from cache

  - Installing symfony/debug (v3.0.9)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.3.0)
    Loading from cache

  - Installing symfony/console (v2.8.15)
    Loading from cache

  - Installing symfony/finder (v2.8.15)
    Loading from cache

  - Installing symfony/filesystem (v2.8.15)
    Loading from cache

  - Installing symfony/yaml (v2.8.15)
    Loading from cache

  - Installing symfony/process (v2.8.15)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache
```

**Comment by aik099** [comment] 2016-12-19 15:29
> The first bad is: 735b416

Are you sure. That commit doesn't even change the code.

My best bet would be the change from PHP-Parser 0.9.4 to 1.4.1 introduced the problem

**Comment by aik099** [comment] 2016-12-19 15:34
According to https://github.com/nikic/PHP-Parser/blob/master/doc/2_Usage_of_basic_components.markdown the `namespacedName` attribute should always be present, when `NameResolver` is used. If I'm not mistaken (haven't looked at the code recently) it is used. According to user comments I've found online the `namespacedName` won't be provided for anonymous classes.

**Comment by esemve** [comment] 2016-12-20 13:28
Sorry but i don't understand. Can you fix it, or it's a bug in the php parser? :) Or it's a "feature", and I must use 1.4?

**Comment by aik099** [comment] 2016-12-20 15:06
I'm unable to fix it due lack of free time, that I can allocate to FOSS projects.

Obviously this is a bug somewhere, because it worked before. You're welcome to send PR with a fix.

**Comment by aik099** [comment] 2016-12-24 14:14
I'm unable to reproduce this locally. Here is my setup:

1. PHP 5.5 or PHP 7.0
2. removed `{{ block('search_index') }}` from `/Sami/Resources/themes/default/search.twig` (or otherwise I will get an exception)
3. try to generate documentation

**Comment by fabpot** [comment] 2017-01-05 21:04
Closing as I'm not able to replicate either with the current master branch.

**Closed by fabpot** 2017-01-05 21:04 UTC

**Comment by fantiq** [comment] 2017-07-07 17:36
i replicate this bug , it is because the `anonymous class`  in source file. like the follow code 
```
class Foo
{
    public function bar()
    {
        $class = new class() {};
    }
}
```

the `sami` will analysis the anonymous class as a normal class, but the  anonymous class has not name and namespace ？

**Comment by Stolz** [comment] 2017-07-13 07:35
Thanks @fantiq. After several months I can finally generate the docs of my project again. Commenting out all the anonymous classes did the trick.
