### ISSUE TITLE
Undefined property: PhpParser\Node\Stmt\Interface_::$type

### ISSUE THREAD

**Issue by bantu** [FriendsOfPHP/Sami#159] opened 2015-04-02 11:11 UTC
Attempting to update Sami for phpBB to 3.0.2, I get `Notice: Undefined property: PhpParser\Node\Stmt\Interface_::$type in [...]/Sami/Parser/NodeVisitor.php line 114`

**Comment by aik099** [comment] 2015-04-02 11:49
1. This is line https://github.com/FriendsOfPHP/Sami/blob/master/Sami/Parser/NodeVisitor.php#L114 you're talking about, right?
2. Could you also show the file contents (via gist I guess, or on GitHub) for which that error was reported?

**Comment by bantu** [comment] 2015-04-02 12:23
@aik099 
Yes, that line.
Sami shows "phpbb\permissions" as the last object under inspection. That would be https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/phpbb/permissions.php

**Comment by bantu** [comment] 2015-04-02 12:26
https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/Interface_.php no $type
https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/ClassLike.php no $type
https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt.php no $type
https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/NodeAbstract.php no $type, last class, this has getType() though.

**Comment by aik099** [comment] 2015-04-02 12:30
But then this error should happen in case if any class/interface is encountered. Probably some not changed code when migration to newer PHP-Parser was made.

**Comment by bantu** [comment] 2015-04-02 12:38
Note that some other class have $type, e.g. https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Stmt/Property.php#L11

Probably getType should be used since that is part of the interface. Didn't look into it too deep, though.

**Comment by white-gecko** [comment] 2015-04-04 11:22
I'm getting the same exception. Is there any further information needed?

**Comment by white-gecko** [comment] 2015-04-04 11:26
I can reproduce the issue with v3.0.0 until dev-master

**Comment by bluescreen** [comment] 2015-04-08 07:14
I can confirm this bug. Any chance this issue will be fixed soon? 
Maybe you could downgrade the php parser version.

**Comment by aik099** [comment] 2015-04-08 07:29
No easy way to downgrade. As I said before we need to find the PR that did the upgrade and figure out what needs to be changed.

**Comment by bluescreen** [comment] 2015-04-08 07:35
Not sure if i broke some features but if just comment the line 114 in NodeVisitor.php it seems at least to run and generate the docs.

**Comment by aik099** [comment] 2015-04-08 07:44
> Not sure if this breaks some features

Surely it does. Because now the modifiers aren't set then final/abstract classes modifier is lost.

**Comment by sarcher** [comment] 2015-04-16 18:10
Replacing this with `getType()` is enough to generate the documentation, but it doesn't seem to be correct; inherited documentation, for example, doesn't seem to work properly. So the fix is likely more complex than that.

**Comment by vincentdieltiens** [comment] 2015-04-17 09:37
Nothing new about this ?

**Comment by aik099** [comment] 2015-04-17 09:44
Nope, unless somebody is willing to dig into commits that made NParser upgrade and figure out what would the proper way of fixing this. I was recommending this in several previous comments already.

**Comment by aik099** [comment] 2015-04-17 09:45
Unfortunately there are not tests in place to verify that documentation is generated properly so no easy way to test this too. Probably comparing documentation generated by previous version os Sami (hopefully using bootstrap theme) and fixed version would tell if anything is missing.

**Comment by aik099** [comment] 2015-04-17 12:43
If I'm not mistaken, then 1a57b9b3590587940c23e00e7ad6e351fcf44e94 commit did the upgrade.

**Comment by pCoLaSD** [comment] 2015-04-17 14:03
This is a BC break of the dependant package `nikic/php-parser`.

Since `v1.2.0` the magic interface was removed from [NodeAbstract.php](https://github.com/nikic/PHP-Parser/blob/v1.1.0/lib/PhpParser/NodeAbstract.php). That's why any call to get a property (e.g. `$type`) will result in an `ErrorException`. A quick solution would be to limit the constraint for `nikic/php-parser` to something like `>=1.0 <1.2`.

**Comment by Rask** [comment] 2015-05-12 05:43
I'm getting the same issue with Traits:

```
[ErrorException]                                                                                                          
Notice: Undefined property: PhpParser\Node\Stmt\Trait_::$type in /[snip]/vendor/sami/sami/Sami/Parser/NodeVisitor.php line 114 
```

My codebase has a single trait with the following structure:

```php
<?php namespace Wow;

trait SuchTrait
{
    protected function veryMethod()
    {
        ...
    }
}
```

Changed the `NodeVisitor.php` as suggested in the PR #164, and the documentation generation works properly again.

**Comment by kdocki** [comment] 2015-05-14 17:36
Seeing this issue as well... +1

**Closed** 2015-05-20 16:45 UTC

**Comment by brunowego** [comment] 2015-05-23 14:11
+1

**Comment by nuhh** [comment] 2015-10-03 19:20
+1 still has issue

**Comment by Stolz** [comment] 2017-02-28 06:57
Using Sami 4.0.1-DEV and still have the same issue
