### ISSUE TITLE
Issue with function signatures

### ISSUE THREAD

**Issue by hadisajj2** [FriendsOfPHP/Sami#245] opened 2016-11-15 22:59 UTC
I have some php files. I am able to run SAMI with no issue. The html output outputs the class hierarchy etc. correctly. Function comments are also generated correctly, however function variables (signature) is not correctly documented. As an example, I have the following piece of code with the comments:

/**
     * Downloads a file.
     *
     * @param string $file         is the name of the object to be downloaded
     * @param string $saveLocation is the location that the dowloaded object will be stored locally
     *
     * @return string[]|null
     */

  public function downloadFile($file, $saveLocation, $s3 = null){
   ...//some code hhere
  }

The comment: "Downloads here" and the return value show up correctly on the html output, however I can't get the comments of the params along with their type to show up. I am trying to mimic examples from symphony: 

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Asset/PathPackage.php

Any help would be appreciated!

**Comment by aik099** [comment] 2016-11-16 07:58
What is the problem, I'm not getting. Do you miss `$s3` parameter in generated doc?

**Comment by hadisajj2** [comment] 2016-11-17 22:30
No what I'm trying to say is that the comments I put for the variables don't show up on the generated document, as in comments for $file should say:
$file is the name of the object to be downloaded

etc. 

In my composer, due to ubuntu version issues, I'm using version 3.3.0 (under require-dev in composer)

**Comment by xelan** [comment] 2017-05-30 06:41
`@Param` should be lowercase, and the documentation should be immediately before the method (no blank line in between).

**Comment by aik099** [comment] 2017-05-30 08:14
Valid point @xelan . That really can confuse DocBlock parser.

**Comment by fabpot** [comment] 2017-07-25 10:47
Closing as this is not a bug as explained by @xelan

**Closed by fabpot** 2017-07-25 10:47 UTC
