### ISSUE TITLE
API docs show wrong list of available classes for branch

### ISSUE THREAD

**Issue by mvdbos** [FriendsOfPHP/Sami#62] opened 2013-11-12 15:41 UTC
Didn't know where to post this issue, here or in the Symfony docs repo. I'm guessing this is a generator bug.

As can be seen in this screenshot, in the list of available HttpExceptions for the 2.1 branch in the sidebar, a lot of Exceptions listed were introduced in a later version. The page shown when clicking on the namespace Symfony\Component\HttpKernel\Exception shows the correct list of available HttpExceptions.

Screenshot:
![sf21-api-docs](https://f.cloud.github.com/assets/1101757/1521822/4d36c9fa-4b9b-11e3-8767-e98c69a376f8.png)

I haven't checked if this is limited to this namespace for this branch or if this is more widespread and related to Sami.

**Comment by bantu** [comment] 2015-01-06 20:10
Is anyone familiar with the codebase interested in resolving this issue anytime soon? cc @GrahamCampbell

@fabpot As per the above, this also seems to affect Symfony.

@mvdbos Is there a downstream ticket in Symfony for this?

**Comment by tractorcow** [comment] 2017-11-07 21:25
Also running into this issue; This is a rather critical bug! I've attempted to debug this, but haven't yet got to the cause of this.

My feeling is that it's likely due to twig's internal cache mistakenly "hitting" on repeated regeneration of templates across multiple branches, or some other over-eager cache check.

**Comment by tractorcow** [comment] 2017-11-07 21:47
Oh, that's interesting... I've made some progress.

Sami\Renderer\Renderer::getTree() uses a SplObjectStorage() as a cache, and uses the Project as the key.

the problem is that the same project is used for multiple versions.

Switching this to an array cache, and using `$project->getVersion()->getName()` as the key fixes the menu issue. :)

However, cached templates are still showing the wrong classes in namespace... will debug further. :)

**Comment by tractorcow** [comment] 2017-11-07 21:56
Horray, I got it working:

 - Fixed getTree() cache (fixes menu)
 - Remove $previousParse / $previousRender from Project::update()
 - Ensure we `initialize()` in Project::switchVersion()
 
 Yes this is less performant, but if a cache introduced invalid content, it's not valuable.

**Comment by tractorcow** [comment] 2017-11-07 22:44
PR at https://github.com/FriendsOfPHP/Sami/pull/311

**Closed** 2017-11-09 05:20 UTC
