### ISSUE TITLE
Render doc even with phpdoc errors?

### ISSUE THREAD

**Issue by althaus** [FriendsOfPHP/Sami#272] opened 2017-04-04 09:36 UTC
Hi,

I'm currently trying to use sami, but it's not rendering anything. We've got some legacy code with invalid phpdoc which results in errors listed by the  `parse` command. Running  `render` afterwards leads to no html file rendered at all:

```
php sami.phar update sami.config.php
Updating project

Version master
  Rendering  0%
            Global index.html
```

Using verbose or not doesn't change anything. Are the doc errors the reason for this or is it something else?

Cheers
Matthias

**Comment by danakil** [comment] 2017-04-12 13:36
Hi,
I have the same problem. I use the latest sami.phar (Sami 4.0.1-DEV). I set up a config file and everything seems to works (it parsed files and detected some errors that I've fixed). After that, it just display:
Rendering  0%                                                  
Global index.html

My build directory only contanis "css/js/fonts" directory and PROJECT_VERSION and SAMI_VERSION files. I didn't set any theme but I suppose there is one built-in by default.

**Comment by danakil** [comment] 2017-04-12 14:15
An edit to my preview comment. I downloaded the source for the latest 4.x version and did a composer.phar update
but
`This package requires php >=7.0 but your PHP version (5.6.11) does not satisfy that requirement.`
So I downloaded the latest 3.x source code, did a composer.phar update then 
`php sami.php update ./config.php -v`
And everything worked fine

So I think that the problem is the php version, but I'm not really sure because the parsing works fine with the latest 4.x phar.

**Comment by dubaaron** [comment] 2017-06-30 01:17
Had the same exact problem, trying to build twig documentation, using sami.phar 4.0.4-DEV, with php 5.6.    

No warning or anything that it hadn't actually completed, was puzzled by the build dir with only css/js/fonts, etc. 

Tried Sami 4.04 with PHP 7, worked just fine.

Also, tried Sami 3.3.0 (latest 3.x as of this writing) with PHP 5.6, and also worked fine.  

NB: Sami 3.3.0 has a bug with incorrectly rendering italics (a la markdown) when underscores occur _inside_ of words, which causes problems when there are parameter names, or other things inside docblocks, that include underscores inside of words. 

Thank you very much.

**Comment by fabpot** [comment] 2017-07-25 10:45
Closing as apparently this is due to a wrong PHP version, which must be 7 for Sami 4.

**Closed by fabpot** 2017-07-25 10:45 UTC
